version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8080"
    volumes:
     - .:/main
    depends_on:
     - db
    environment:
      SPORK_HOST: "http://localhost:8000"
  db:
    image: "postgres:10"
    ports:
      - "5432:5432"
    env_file:
      - ./secrets.env
